---
deployment:
  tasks:
    # Create necessary directories if they don't exist
    - export DEPLOYPATH=/home/public_html/hr.qlabs.pk
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/assets/uploads/resumes
    
    # Copy all files to deployment path
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp .gitignore $DEPLOYPATH/
    
    # Set proper permissions
    - /bin/chmod 755 $DEPLOYPATH/functions
    - /bin/chmod 755 $DEPLOYPATH/assets
    - /bin/chmod 755 $DEPLOYPATH/assets/uploads
    - /bin/chmod 777 $DEPLOYPATH/assets/uploads/resumes
    
    # Create database file if it doesn't exist
    - /bin/touch $DEPLOYPATH/db.sqlite
    - /bin/chmod 666 $DEPLOYPATH/db.sqlite
    
    # Run database migration (only on first deploy or when schema changes)
    # Uncomment the line below if you need to run migration
    # - /usr/bin/php $DEPLOYPATH/migrate.php
    
    # Clean up temporary files
    - /bin/rm -f $DEPLOYPATH/check.php
    - /bin/rm -f $DEPLOYPATH/TESTING.md
